// FILE: cortex-lab/config.js
// Harness X — central config + run-ID + mode parsing.
// Never imports any product code. Pure CLI/env layer.

'use strict';

const crypto = require('crypto');
const path   = require('path');

const VALID_MODES = ['static', 'dry-run', 'live', 'red-team', 'all'];

function parseArgs(argv) {
  const args = { mode: 'static', loop: false, autoFix: false, only: null };
  for (const a of argv.slice(2)) {
    if (a.startsWith('--mode=')) args.mode = a.slice(7).trim();
    else if (a === '--loop') args.loop = true;
    else if (a === '--auto-fix') args.autoFix = true;
    else if (a.startsWith('--only=')) args.only = a.slice(7).trim();
  }
  if (!VALID_MODES.includes(args.mode)) {
    console.error(`[harness] Unknown mode "${args.mode}". Valid: ${VALID_MODES.join(', ')}`);
    process.exit(2);
  }
  return args;
}

function newRunId() {
  const ts  = Date.now().toString(36);
  const rnd = crypto.randomBytes(4).toString('hex');
  return `ctx_${ts}_${rnd}`;
}

const ROOT = path.resolve(__dirname);

function load(argv = process.argv) {
  // Load env in priority order (later calls win because dotenv skips already-set vars by default,
  // but we use `override: true` for .env.test so test credentials take precedence over .env).
  try { require('dotenv').config({ path: path.join(ROOT, '..', '.env') }); } catch { /* dotenv optional */ }
  // cortex-lab/.env.test overrides — generated by scripts/generate-test-tokens.js, gitignored.
  try { require('dotenv').config({ path: path.join(ROOT, '.env.test'), override: true }); } catch { /* optional */ }

  const args = parseArgs(argv);
  return {
    args,
    runId:        process.env.CORTEX_TEST_RUN_ID || newRunId(),
    rootDir:      ROOT,
    scenariosDir: path.join(ROOT, 'scenarios'),
    resultsDir:   path.join(ROOT, 'results'),
    reportsDir:   path.join(ROOT, 'reports'),
    env: {
      nodeEnv:                process.env.NODE_ENV || 'development',
      supabaseUrl:            process.env.SUPABASE_URL              || null,
      supabaseKey:            process.env.SUPABASE_KEY              || process.env.SUPABASE_SERVICE_ROLE_KEY || null,
      databaseUrl:            process.env.DATABASE_URL              || null,
      testBaseUrl:            process.env.CORTEX_TEST_BASE_URL      || null,
      testSupabaseUrl:        process.env.CORTEX_TEST_SUPABASE_URL  || null,
      testSupabaseKey:        process.env.CORTEX_TEST_SUPABASE_KEY  || null,
      ownerAToken:            process.env.CORTEX_TEST_TOKEN_OWNER_A || null,
      staffAToken:            process.env.CORTEX_TEST_TOKEN_STAFF_A || null,
      ownerBToken:            process.env.CORTEX_TEST_TOKEN_OWNER_B || null,
      allowWrite:             process.env.CORTEX_TEST_DB_ALLOW_WRITE === 'true',
      requireNonProd:         process.env.CORTEX_TEST_REQUIRE_NON_PROD !== 'false', // default ON
      allowProd:              process.env.CORTEX_TEST_ALLOW_PROD === 'I-UNDERSTAND',
      realLLM:                process.env.CORTEX_TEST_REAL_LLM === 'true',
      autoFix:                process.env.CORTEX_HARNESS_AUTO_FIX === 'true',
      externalSendEnabled:    process.env.FEATURE_EXTERNAL_MESSAGE_SENDING_ENABLED === 'true',
    },
    // Hosts that look like production. Any match → live writes are blocked
    // unless allowProd === true (founder-only override).
    // Exact production hostnames. Railway appends "-production" to environment names
    // so staging services like "vantro-node-staging-production.up.railway.app" are NOT blocked.
    // Only the real production backend "vantro-flow-backend-production.up.railway.app" is.
    prodHostDenylist: [
      'vantro-flow-backend-production.up.railway.app',
      'flow.vantro.ai',
      'app.vantro.ai',
      'api.vantro.ai',
    ],
  };
}

module.exports = { load, newRunId, VALID_MODES };
